In [104]:
!python --version

Python 3.11.6

In [105]:
!pip list

Package                       Version
----------------------------- ------------
alembic                       1.12.0
anyio                         4.0.0
argon2-cffi                   23.1.0
argon2-cffi-bindings          21.2.0
arrow                         1.3.0
asttokens                     2.4.0
async-generator               1.10
async-lru                     2.0.4
attrs                         23.1.0
Babel                         2.13.0
backcall                      0.2.0
backports.functools-lru-cache 1.6.5
beautifulsoup4                4.12.2
bleach                        6.1.0
blinker                       1.6.3
boltons                       23.0.0
Brotli                        1.1.0
cached-property               1.5.2
certifi                       2023.7.22
certipy                       0.1.3
cffi                          1.16.0
charset-normalizer            3.3.0
colorama                      0.4.6
comm                          0.1.4
conda                         23.9.0
conda-package-handling        2.2.0
conda_package_streaming       0.9.0
cryptography                  41.0.4
debugpy                       1.8.0
decorator                     5.1.1
defusedxml                    0.7.1
duckdb                        1.4.4
entrypoints                   0.4
exceptiongroup                1.1.3
executing                     1.2.0
fastjsonschema                2.18.1
fqdn                          1.5.1
greenlet                      3.0.0
idna                          3.4
importlib-metadata            6.8.0
importlib-resources           6.1.0
ipykernel                     6.25.2
ipython                       8.16.1
ipython-genutils              0.2.0
isoduration                   20.11.0
jedi                          0.19.1
Jinja2                        3.1.2
json5                         0.9.14
jsonpatch                     1.33
jsonpointer                   2.4
jsonschema                    4.19.1
jsonschema-specifications     2023.7.1
jupyter_client                8.4.0
jupyter_core                  5.4.0
jupyter-events                0.8.0
jupyter-lsp                   2.2.0
jupyter_server                2.8.0
jupyter_server_terminals      0.4.4
jupyter-telemetry             0.1.0
jupyterhub                    4.0.2
jupyterlab                    4.0.7
jupyterlab-pygments           0.2.2
jupyterlab_server             2.25.0
libmambapy                    1.5.2
Mako                          1.2.4
mamba                         1.5.2
MarkupSafe                    2.1.3
matplotlib-inline             0.1.6
mistune                       3.0.1
nbclassic                     1.0.0
nbclient                      0.8.0
nbconvert                     7.9.2
nbformat                      5.9.2
nest-asyncio                  1.5.8
notebook                      7.0.6
notebook_shim                 0.2.3
numpy                         2.4.2
oauthlib                      3.2.2
overrides                     7.4.0
packaging                     23.2
pamela                        1.1.0
pandas                        3.0.0
pandocfilters                 1.5.0
parso                         0.8.3
pexpect                       4.8.0
pickleshare                   0.7.5
pip                           23.3
pkgutil_resolve_name          1.3.10
platformdirs                  3.11.0
pluggy                        1.3.0
prometheus-client             0.17.1
prompt-toolkit                3.0.39
psutil                        5.9.5
psycopg2-binary               2.9.11
ptyprocess                    0.7.0
pure-eval                     0.2.2
pyarrow                       23.0.0
pycosat                       0.6.6
pycparser                     2.21
pycurl                        7.45.1
Pygments                      2.16.1
PyJWT                         2.8.0
pyOpenSSL                     23.2.0
PySocks                       1.7.1
python-dateutil               2.8.2
python-json-logger            2.0.7
pytz                          2023.3.post1
PyYAML                        6.0.1
pyzmq                         25.1.1
referencing                   0.30.2
requests                      2.31.0
rfc3339-validator             0.1.4
rfc3986-validator             0.1.1
rpds-py                       0.10.6
ruamel.yaml                   0.17.39
ruamel.yaml.clib              0.2.7
Send2Trash                    1.8.2
setuptools                    68.2.2
six                           1.16.0
sniffio                       1.3.0
soupsieve                     2.5
SQLAlchemy                    2.0.22
stack-data                    0.6.2
terminado                     0.17.1
tinycss2                      1.2.1
tomli                         2.0.1
tornado                       6.3.3
tqdm                          4.66.1
traitlets                     5.11.2
truststore                    0.8.0
types-python-dateutil         2.8.19.14
typing_extensions             4.8.0
typing-utils                  0.1.0
uri-template                  1.3.0
urllib3                       2.0.7
wcwidth                       0.2.8
webcolors                     1.13
webencodings                  0.5.1
websocket-client              1.6.4
wheel                         0.41.2
zipp                          3.17.0
zstandard                     0.21.0

## Model Pipeline

### 1. Load Raw Data

In [106]:
import os
from sqlalchemy import create_engine

print("DATABASE_URL =", os.getenv("DATABASE_URL"))

engine = create_engine(os.getenv("DATABASE_URL"))
print("dialect =", engine.dialect.name)
print("driver  =", engine.dialect.driver)

DATABASE_URL = postgresql+psycopg2://datateam:jipjipmoneydata@192.168.1.111:5432/jipjipmoney
dialect = postgresql
driver  = psycopg2

In [107]:
import os
import pandas as pd
import duckdb
from sqlalchemy import create_engine
import numpy as np
import psycopg2
from io import StringIO
from urllib.parse import urlparse

engine = create_engine(os.getenv("DATABASE_URL"))

conn = engine.raw_connection()
try:
    df = pd.read_sql(
        "SELECT * FROM jjm_customer_loan where type = 'Bag' and status = 1 order by form_id",
        conn
    )
finally:
    conn.close()

/tmp/ipykernel_283/2060821619.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(

In [108]:
# บันทึกข้อมูลที่เป็น raw เก็บไว้ที่ bronze
df.to_parquet(
    "/home/jovyan/database/bronze/bronze_jjm_customer_loan.parquet",
    index=False
)

#### Load Data on Bronze Warehouse

In [109]:
# =========================
# 1) CONNECT WAREHOUSE
# =========================
url = os.getenv("DATABASE_WAREHOUSE")
p = urlparse(url)

conn = psycopg2.connect(
    host=p.hostname,
    port=p.port,
    user=p.username,
    password=p.password,
    dbname=p.path.lstrip("/")
)
cur = conn.cursor()

# =========================
# 2) CREATE SCHEMA + TABLE
# =========================
cur.execute("CREATE SCHEMA IF NOT EXISTS bronze;")

cur.execute("""
CREATE TABLE IF NOT EXISTS bronze.jjm_customer_loan (
    form_id               INTEGER,
    transaction_date      TIMESTAMPTZ,
    contract_num          VARCHAR(20),
    data_source           CHAR(20),
    jewelry_type          VARCHAR(100),
    type                  VARCHAR(255),
    brand                 VARCHAR(255),
    model                 VARCHAR(255),
    sub_model             VARCHAR(255),
    size                  VARCHAR(255),
    color                 VARCHAR(255),
    hardware              VARCHAR(255),
    material              VARCHAR(255),
    code                  VARCHAR(255),
    year_stamp_holo_dc    VARCHAR(255),
    product_year          VARCHAR(100),
    condition             TEXT,
    accessory             TEXT,
    accessory_info        TEXT,
    duration              SMALLINT,
    estimate_amount       NUMERIC(20,2),
    received_amount       NUMERIC(20,2),
    picture_url           TEXT,
    status                SMALLINT,
    editor                VARCHAR(100),
    updated_at            TIMESTAMP,
    actual_price          INTEGER,
    actualprice_status    SMALLINT,
    actualprice_editor    VARCHAR(100),
    used_price            SMALLINT,
    condition_backup      TEXT,
    year_letter           TEXT
);
""")

# overwrite bronze (bronze = raw snapshot)
cur.execute("TRUNCATE TABLE bronze.jjm_customer_loan;")

# =========================
# 3) PREPARE DATAFRAME
# =========================
df = df.copy()

# ---- INTEGER / SMALLINT columns ----
int_like_cols = [
    "form_id",
    "actual_price",
    "estimate_amount",
    "status",
    "actualprice_status",
    "used_price",
    "duration",
]

for col in int_like_cols:
    if col in df.columns:
        df[col] = (
            df[col]
            .astype("Int64")    # pandas nullable int
            .astype("object")   # prevent "1.0"
        )

# =========================
# 4) SERIALIZE TO CSV
# =========================
buffer = StringIO()
df.to_csv(
    buffer,
    index=False,
    header=False,
    na_rep="\\N"   # explicit NULL marker
)
buffer.seek(0)

# =========================
# 5) COPY WITH COLUMN LIST
# =========================
cur.copy_expert(
    """
    COPY bronze.jjm_customer_loan (
        form_id,
        transaction_date,
        contract_num,
        data_source,
        jewelry_type,
        type,
        brand,
        model,
        sub_model,
        size,
        color,
        hardware,
        material,
        code,
        year_stamp_holo_dc,
        product_year,
        condition,
        accessory,
        accessory_info,
        duration,
        estimate_amount,
        received_amount,
        picture_url,
        status,
        editor,
        updated_at,
        actual_price,
        actualprice_status,
        actualprice_editor,
        used_price,
        condition_backup,
        year_letter
    )
    FROM STDIN
    WITH (FORMAT CSV, NULL '\\N')
    """,
    buffer
)

# =========================
# 6) COMMIT + CLOSE
# =========================
conn.commit()
cur.close()
conn.close()

print("Data successfully loaded into bronze.jjm_customer_loan.")

Data successfully loaded into bronze.jjm_customer_loan.

In [110]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6906 entries, 0 to 6905
Data columns (total 32 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   form_id             6906 non-null   object
 1   transaction_date    6906 non-null   datetime64[us, UTC]
 2   contract_num        4808 non-null   str
 3   data_source         6906 non-null   str
 4   jewelry_type        577 non-null    str
 5   type                6906 non-null   str
 6   brand               6906 non-null   str
 7   model               6906 non-null   str
 8   sub_model           6906 non-null   str
 9   size                6906 non-null   str
 10  color               6906 non-null   str
 11  hardware            6906 non-null   str
 12  material            6906 non-null   str
 13  code                577 non-null    str
 14  year_stamp_holo_dc  6196 non-null   str
 15  product_year        1795 non-null   str
 16  condition           6906 non-null   str
 17  accessory           6660 non-null   str
 18  accessory_info      3969 non-null   str
 19  duration            6906 non-null   object
 20  estimate_amount     6562 non-null   object
 21  received_amount     4453 non-null   float64
 22  picture_url         6906 non-null   str
 23  status              6906 non-null   object
 24  editor              6906 non-null   str
 25  updated_at          6906 non-null   datetime64[us]
 26  actual_price        6528 non-null   object
 27  actualprice_status  6585 non-null   object
 28  actualprice_editor  5958 non-null   str
 29  used_price          5958 non-null   object
 30  condition_backup    6906 non-null   str
 31  year_letter         759 non-null    str
dtypes: datetime64[us, UTC](1), datetime64[us](1), float64(1), object(7), str(22)
memory usage: 6.2+ MB

### 2. Data Cleaning

#### Clean column name ( snake_case )

In [111]:
import re

df.columns = (
    df.columns
      .str.strip()                              # ตัด space หน้า-หลัง
      .str.lower()                              # เป็น lowercase
      .str.replace(r"[^\w]+", "_", regex=True)  # แทนที่อักขระแปลกด้วย _
      .str.replace(r"_+", "_", regex=True)      # รวม _ ซ้ำ
      .str.strip("_")                           # ตัด _ หน้า-หลัง
)

In [112]:
df.columns.tolist()

['form_id',
 'transaction_date',
 'contract_num',
 'data_source',
 'jewelry_type',
 'type',
 'brand',
 'model',
 'sub_model',
 'size',
 'color',
 'hardware',
 'material',
 'code',
 'year_stamp_holo_dc',
 'product_year',
 'condition',
 'accessory',
 'accessory_info',
 'duration',
 'estimate_amount',
 'received_amount',
 'picture_url',
 'status',
 'editor',
 'updated_at',
 'actual_price',
 'actualprice_status',
 'actualprice_editor',
 'used_price',
 'condition_backup',
 'year_letter']

#### Seclect Colunm

In [113]:
df_col = df[["contract_num","form_id", "brand", "model", "sub_model", "size", "color", "hardware", "material", "condition", "year_stamp_holo_dc", "product_year" ,"estimate_amount","actual_price"]]

df_col.head()

,contract_num,form_id,brand,model,sub_model,size,color,hardware,material,condition,year_stamp_holo_dc,product_year,estimate_amount,actual_price
0,NaN,6,LOUIS VUITTON,Malle,Malle,Petite 20,Brown,Gold,Canvas,95-98% เหมือนใหม่ (Like New) มีร่องรอยเพียงเล็...,-,NaN,80000,80000
1,NaN,7,CHRISTIAN DIOR,Lady Dior,Lady Dior,Mini 17,Black,Silver,Satin,95-98% เหมือนใหม่ (Like New) มีร่องรอยเพียงเล็...,NaN,NaN,65000,65000
2,NaN,9,LOUIS VUITTON,Noe,Neonoe,BB,Monogram,Gold,Canvas,79-70% (Damaged) ทรงเปลี่ยนชัดเจน สีเฟดชัดเจน ...,2016,NaN,40000,40000
3,2566000039.0,11,CHRISTIAN DIOR,Saddle,Saddle,Mini 20,Red,Gold,Calfskin,100% (New) สินค้าใหม่ ไม่เคยผ่านการใช้งาน และอ...,Mo447wEVG,NaN,60000,60000
4,2566000040.0,12,CHRISTIAN DIOR,Be Dior,Be Dior,Small 27,Beige,Gold,Calfskin,95-98% เหมือนใหม่ (Like New) มีร่องรอยเพียงเล็...,M09810TRL,NaN,50000,50000

#### Cast Data Type

In [114]:
cols = [
    "contract_num",
    "form_id",
    "brand",
    "model",
    "sub_model",
    "size",
    "color",
    "hardware",
    "material",
    "condition",
    "year_stamp_holo_dc",
    "product_year",
    "estimate_amount",
    "actual_price"
]

df_col = df[cols].copy()

In [115]:
text_cols = [
    "contract_num",
    "brand",
    "model",
    "sub_model",
    "size",
    "color",
    "hardware",
    "material",
    "condition",
    "year_stamp_holo_dc",
    "product_year",
]

df_col[text_cols] = df_col[text_cols].astype("string")

In [116]:
df_col["form_id"] = df_col["form_id"].astype("Int64")
df_col["estimate_amount"] = df_col["estimate_amount"].astype("Int64")
df_col["actual_price"] = df_col["actual_price"].astype("Int64")

In [117]:
df_col.info()

<class 'pandas.DataFrame'>
RangeIndex: 6906 entries, 0 to 6905
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   contract_num        4808 non-null   string
 1   form_id             6906 non-null   Int64
 2   brand               6906 non-null   string
 3   model               6906 non-null   string
 4   sub_model           6906 non-null   string
 5   size                6906 non-null   string
 6   color               6906 non-null   string
 7   hardware            6906 non-null   string
 8   material            6906 non-null   string
 9   condition           6906 non-null   string
 10  year_stamp_holo_dc  6196 non-null   string
 11  product_year        1795 non-null   string
 12  estimate_amount     6562 non-null   Int64
 13  actual_price        6528 non-null   Int64
dtypes: Int64(3), string(11)
memory usage: 2.4 MB

In [118]:
df_col.head()

,contract_num,form_id,brand,model,sub_model,size,color,hardware,material,condition,year_stamp_holo_dc,product_year,estimate_amount,actual_price
0,<NA>,6,LOUIS VUITTON,Malle,Malle,Petite 20,Brown,Gold,Canvas,95-98% เหมือนใหม่ (Like New) มีร่องรอยเพียงเล็...,-,<NA>,80000,80000
1,<NA>,7,CHRISTIAN DIOR,Lady Dior,Lady Dior,Mini 17,Black,Silver,Satin,95-98% เหมือนใหม่ (Like New) มีร่องรอยเพียงเล็...,<NA>,<NA>,65000,65000
2,<NA>,9,LOUIS VUITTON,Noe,Neonoe,BB,Monogram,Gold,Canvas,79-70% (Damaged) ทรงเปลี่ยนชัดเจน สีเฟดชัดเจน ...,2016,<NA>,40000,40000
3,2566000039.0,11,CHRISTIAN DIOR,Saddle,Saddle,Mini 20,Red,Gold,Calfskin,100% (New) สินค้าใหม่ ไม่เคยผ่านการใช้งาน และอ...,Mo447wEVG,<NA>,60000,60000
4,2566000040.0,12,CHRISTIAN DIOR,Be Dior,Be Dior,Small 27,Beige,Gold,Calfskin,95-98% เหมือนใหม่ (Like New) มีร่องรอยเพียงเล็...,M09810TRL,<NA>,50000,50000

#### Format Clean

In [119]:
import re
import pandas as pd

def format_text_lock_word_caps(s: pd.Series) -> pd.Series:
    s = (
        s.astype("string")
         .str.strip()
         .str.replace(r"\s+", " ", regex=True)
         .str.replace(r"\s*([\/\-.])\s*", r"\1", regex=True)
    )

    def _fmt(x):
        if pd.isna(x):
            return x

        words = x.split(" ")
        formatted_words = []

        for w in words:
            # ถ้าเป็น ALL CAPS ทั้งคำ → คงไว้
            if w.isupper():
                formatted_words.append(w)
            else:
                formatted_words.append(w.lower().title())

        x = " ".join(formatted_words)

        # หลัง / - . ให้ตัวแรกเป็นตัวใหญ่
        x = re.sub(
            r"([\/\-.])([a-zA-Z])",
            lambda m: m.group(1) + m.group(2).upper(),
            x,
        )

        return x

    return s.apply(_fmt)

In [120]:
df_col.head()

,contract_num,form_id,brand,model,sub_model,size,color,hardware,material,condition,year_stamp_holo_dc,product_year,estimate_amount,actual_price
0,<NA>,6,LOUIS VUITTON,Malle,Malle,Petite 20,Brown,Gold,Canvas,95-98% เหมือนใหม่ (Like New) มีร่องรอยเพียงเล็...,-,<NA>,80000,80000
1,<NA>,7,CHRISTIAN DIOR,Lady Dior,Lady Dior,Mini 17,Black,Silver,Satin,95-98% เหมือนใหม่ (Like New) มีร่องรอยเพียงเล็...,<NA>,<NA>,65000,65000
2,<NA>,9,LOUIS VUITTON,Noe,Neonoe,BB,Monogram,Gold,Canvas,79-70% (Damaged) ทรงเปลี่ยนชัดเจน สีเฟดชัดเจน ...,2016,<NA>,40000,40000
3,2566000039.0,11,CHRISTIAN DIOR,Saddle,Saddle,Mini 20,Red,Gold,Calfskin,100% (New) สินค้าใหม่ ไม่เคยผ่านการใช้งาน และอ...,Mo447wEVG,<NA>,60000,60000
4,2566000040.0,12,CHRISTIAN DIOR,Be Dior,Be Dior,Small 27,Beige,Gold,Calfskin,95-98% เหมือนใหม่ (Like New) มีร่องรอยเพียงเล็...,M09810TRL,<NA>,50000,50000

In [121]:
duckdb.query("SELECT condition,count(condition) FROM df_col group by condition order by count(condition)").to_df()

                                           condition  count(condition)
0  ต่ำกว่า 59% (Reconsideration) สินค้าชำรุด หรือ...                86
1  69-60% (Breakage) สภาพทรุดโทรม มีตำหนิหลายจุด ...               180
2  99% ไม่ผ่านการใช้งาน (Kept Unused) ไม่ผ่านการใ...               211
3  100% (New) สินค้าใหม่ ไม่เคยผ่านการใช้งาน และอ...               246
4  84-80% (Poor Condition) ทรงเริ่มเปลี่ยน สีซีดจ...               274
5                                            Unknown               415
6  89-85% (Fair Condition) มีตำหนิชัดเจน เช่น สีซ...               455
7  79-70% (Damaged) ทรงเปลี่ยนชัดเจน สีเฟดชัดเจน ...               861
8  94-90% (Good Condition) ผ่านการใช้งาน มีตำหนิท...              1566
9  95-98% เหมือนใหม่ (Like New) มีร่องรอยเพียงเล็...              2612

In [122]:
df_col.info()

<class 'pandas.DataFrame'>
RangeIndex: 6906 entries, 0 to 6905
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   contract_num        4808 non-null   string
 1   form_id             6906 non-null   Int64
 2   brand               6906 non-null   string
 3   model               6906 non-null   string
 4   sub_model           6906 non-null   string
 5   size                6906 non-null   string
 6   color               6906 non-null   string
 7   hardware            6906 non-null   string
 8   material            6906 non-null   string
 9   condition           6906 non-null   string
 10  year_stamp_holo_dc  6196 non-null   string
 11  product_year        1795 non-null   string
 12  estimate_amount     6562 non-null   Int64
 13  actual_price        6528 non-null   Int64
dtypes: Int64(3), string(11)
memory usage: 2.4 MB

In [123]:
# บันทึกข้อมูลที่ clean เบื้องต้นแล้วเก็บไว้ที่ silver
df.to_parquet(
    "/home/jovyan/database/silver/silver_jjm_customer_loan.parquet",
    index=False
)

#### Load Data on Silver Warehouse

In [124]:
conn = psycopg2.connect(
    host=p.hostname,
    port=p.port,
    user=p.username,
    password=p.password,
    dbname=p.path.lstrip("/")
)
cur = conn.cursor()

cur.execute("CREATE SCHEMA IF NOT EXISTS silver;")

cur.execute(f"""
CREATE TABLE IF NOT EXISTS silver.jjm_customer_loan (
    contract_num        TEXT,
    form_id             INT,
    brand               TEXT,
    model               TEXT,
    sub_model           TEXT,
    size                TEXT,
    color               TEXT,
    hardware            TEXT,
    material            TEXT,
    condition           TEXT,
    year_stamp_holo_dc  TEXT,
    product_year        TEXT,
    estimate_amount     INT,
    actual_price        INT
);
""")

cur.execute("TRUNCATE TABLE silver.jjm_customer_loan;")

buffer = StringIO()
df_col.to_csv(buffer, index=False, header=False)
buffer.seek(0)

cur.copy_expert(
    "COPY silver.jjm_customer_loan FROM STDIN WITH (FORMAT CSV)",
    buffer
)

conn.commit()
cur.close()
conn.close()

print("Data successfully loaded into silver.jjm_customer_loan.")

Data successfully loaded into silver.jjm_customer_loan.

### 3. Transformation Data

#### Map Condition

In [125]:
duckdb.unregister("df_col")  # optional แต่แนะนำ
duckdb.register("df_col", df_col)

In [126]:
sql = """
SELECT
    contract_num,
    form_id,
    brand,
    model,
    sub_model,
    size,
    color,
    hardware,
    material,

    CASE

        WHEN UPPER(brand) = 'HERMES'
            THEN '95-98% เหมือนใหม่ (Like New) มีร่องรอยเพียงเล็กน้อยจากการจัดเก็บหรือทดลองใช้งาน'

        WHEN condition IS NULL THEN NULL

        WHEN regexp_matches(condition, '100\s*[%％]')
            THEN '100% (New) สินค้าใหม่ ไม่เคยผ่านการใช้งาน และออกจากช๊อปไม่เกิน 12 เดือน'

        WHEN regexp_matches(condition, '99\s*[%％]')
            THEN '99% ไม่ผ่านการใช้งาน (Kept Unused) ไม่ผ่านการใช้งาน แต่อุปกรณ์ไม่ครบเหมือนออกจากช๊อป'

        WHEN regexp_matches(condition, '95\s*[-–]\s*98\s*[%％]')
            THEN '95-98% เหมือนใหม่ (Like New) มีร่องรอยเพียงเล็กน้อยจากการจัดเก็บหรือทดลองใช้งาน'

        WHEN regexp_matches(condition, '94\s*[-–]\s*90\s*[%％]')
            THEN '94-90% (Good Condition) ผ่านการใช้งาน มีตำหนิทั่วไป เช่น มุมถลอกหรือรอยขีดเล็กน้อย'

        WHEN regexp_matches(condition, '89\s*[-–]\s*(85|80)\s*[%％]')
            THEN '89-85% (Fair Condition) มีตำหนิชัดเจน เช่น สีซีด มุมถลอก หรือหนังมีรอยชัดเจน'

        WHEN regexp_matches(condition, '84\s*[-–]\s*80\s*[%％]')
            THEN '84-80% (Poor Condition) ทรงเริ่มเปลี่ยน สีซีดจาง หนังเริ่มเสียทรงหรือมีสีเฟดบางส่วน'

        WHEN regexp_matches(condition, '79\s*[-–]\s*70\s*[%％]')
            THEN '79-70% (Damaged) ทรงเปลี่ยนชัดเจน สีเฟดชัดเจน มีรอยถลอกหรือขาดชัดเจน'

        WHEN regexp_matches(condition, '69\s*[-–]\s*60\s*[%％]')
            THEN '69-60% (Breakage) สภาพทรุดโทรม มีตำหนิหลายจุด ผ่านการซ่อม/เปลี่ยนทรง/เปลี่ยนอะไหล่ หรือซ่อมสี'

        WHEN regexp_matches(condition, '(5[0-9]|[0-4][0-9])\s*[%％]')
            THEN 'ต่ำกว่า 59% (Reconsideration) สินค้าชำรุด หรือเปลี่ยนสีทั้งใบ/ทำสี ต้องได้รับการพิจารณาโดยเจ้าหน้าที่ผู้มีอำนาจ'

        ELSE 'Unknown'
    END AS condition,

    year_stamp_holo_dc,
    product_year,
    
    COALESCE(actual_price, estimate_amount) AS estimate_amount

FROM df_col
"""

df_col = duckdb.query(sql).to_df()

regexp_matches(condition, '95\s*[-–]\s*98\s*[%％]')

แปลว่า:

- `95`

- `\s*` → space จะมีหรือไม่ก็ได้

- `[-–]` → dash แบบไหนก็ได้ (`-` หรือ `–`)

- `% หรือ ％`

In [127]:
duckdb.query("SELECT condition,count(condition) FROM df_col group by condition order by count(condition)").to_df()

                                           condition  count(condition)
0  ต่ำกว่า 59% (Reconsideration) สินค้าชำรุด หรือ...                91
1  69-60% (Breakage) สภาพทรุดโทรม มีตำหนิหลายจุด ...               195
2  99% ไม่ผ่านการใช้งาน (Kept Unused) ไม่ผ่านการใ...               256
3  100% (New) สินค้าใหม่ ไม่เคยผ่านการใช้งาน และอ...               297
4  84-80% (Poor Condition) ทรงเริ่มเปลี่ยน สีซีดจ...               307
5                                            Unknown               436
6  89-85% (Fair Condition) มีตำหนิชัดเจน เช่น สีซ...               508
7  79-70% (Damaged) ทรงเปลี่ยนชัดเจน สีเฟดชัดเจน ...               959
8  94-90% (Good Condition) ผ่านการใช้งาน มีตำหนิท...              1776
9  95-98% เหมือนใหม่ (Like New) มีร่องรอยเพียงเล็...              2081

#### Map Colors

In [128]:
import json

with open("/home/jovyan/data/mapping/synthetic_brand_palette.json", "r", encoding="utf-8") as f:
    brand_color_map = json.load(f)

In [129]:
# แปลง Json เป็น DataFrame
rows = []
for brand, colors in brand_color_map.items():
    for color, segment in colors.items():
        rows.append({
            "brand": brand,
            "color": color,
            "color_segment": segment
        })

df_color_map = pd.DataFrame(rows)

In [130]:
df_color_map.head()

    brand      color color_segment
0  CHANEL      Beige       popular
1  CHANEL      Black       popular
2  CHANEL       Grey       popular
3  CHANEL      Green     unpopular
4  CHANEL  Navy Blue     unpopular

In [131]:
# รวมสองตารางตาม brand และ color
df_col = (
    df_col
      .merge(
          df_color_map,
          on=["brand", "color"],
          how="left"
      )
)

# กำหนด default ถ้า map ไม่เจอ
df_col["color_segment"] = df_col["color_segment"].fillna("Unknown")

In [132]:
df_col.head()

,contract_num,form_id,brand,model,sub_model,size,color,hardware,material,condition,year_stamp_holo_dc,product_year,estimate_amount,color_segment
0,NaN,6,LOUIS VUITTON,Malle,Malle,Petite 20,Brown,Gold,Canvas,95-98% เหมือนใหม่ (Like New) มีร่องรอยเพียงเล็...,-,NaN,80000,popular
1,NaN,7,CHRISTIAN DIOR,Lady Dior,Lady Dior,Mini 17,Black,Silver,Satin,95-98% เหมือนใหม่ (Like New) มีร่องรอยเพียงเล็...,NaN,NaN,65000,popular
2,NaN,9,LOUIS VUITTON,Noe,Neonoe,BB,Monogram,Gold,Canvas,79-70% (Damaged) ทรงเปลี่ยนชัดเจน สีเฟดชัดเจน ...,2016,NaN,40000,popular
3,2566000039.0,11,CHRISTIAN DIOR,Saddle,Saddle,Mini 20,Red,Gold,Calfskin,100% (New) สินค้าใหม่ ไม่เคยผ่านการใช้งาน และอ...,Mo447wEVG,NaN,60000,unpopular
4,2566000040.0,12,CHRISTIAN DIOR,Be Dior,Be Dior,Small 27,Beige,Gold,Calfskin,95-98% เหมือนใหม่ (Like New) มีร่องรอยเพียงเล็...,M09810TRL,NaN,50000,popular

#### Map Year

In [133]:
import duckdb

duckdb.register("df_col", df_col)

##### 1. Brand : Chanel

In [134]:
sql = """
SELECT
    *,
    CASE
        WHEN brand = 'CHANEL'
             AND product_year IS NULL
             AND year_stamp_holo_dc IS NOT NULL
        THEN
            CASE
                /* ---------- unknown / junk ---------- */
                WHEN trim(year_stamp_holo_dc) = '' THEN NULL
                WHEN trim(year_stamp_holo_dc) ~ '^-+$' THEN NULL
                WHEN lower(trim(year_stamp_holo_dc)) IN ('n/a','na') THEN NULL
                WHEN trim(year_stamp_holo_dc) IN ('ไม่ระบุ','จำไม่ได้','ไม่ทราบ','ไม่แน่ใจ') THEN NULL

                /* ---------- explicit metal plate ---------- */
                WHEN lower(year_stamp_holo_dc) ~ 'metal\\s*plate'
                THEN 'metal plate'

                /* ---------- (2021) or (2018-2019) ---------- */
                WHEN year_stamp_holo_dc ~ '\\(\\s*(?:19|20)[0-9]{2}'
                THEN regexp_extract(
                        year_stamp_holo_dc,
                        '\\(\\s*((?:19|20)[0-9]{2})',
                        1
                     )

                /* ---------- pure year ---------- */
                WHEN year_stamp_holo_dc ~ '^(19|20)[0-9]{2}$'
                THEN year_stamp_holo_dc

                /* ---------- holo / microchip ---------- */
                WHEN lower(year_stamp_holo_dc) ~ 'holo'
                THEN 'metal plate'

                WHEN lower(trim(year_stamp_holo_dc)) = 'microchip'
                THEN 'metal plate'

                /* ---------- alnum 6–9 chars ---------- */
                WHEN year_stamp_holo_dc ~ '^[A-Za-z0-9]{6,9}$'
                THEN 'metal plate'

                /* ---------- numeric 8-digit serial ---------- */
                WHEN year_stamp_holo_dc ~ '([0-9]{8})'
                THEN
                    CASE
                        SUBSTRING(
                            regexp_extract(
                                year_stamp_holo_dc,
                                '([0-9]{8})',
                                1
                            )
                            FROM 1 FOR 2
                        )
                        WHEN '11' THEN '2006'
                        WHEN '12' THEN '2008'
                        WHEN '13' THEN '2009'
                        WHEN '14' THEN '2010'
                        WHEN '15' THEN '2011'
                        WHEN '16' THEN '2012'
                        WHEN '17' THEN '2012'
                        WHEN '18' THEN '2013'
                        WHEN '19' THEN '2014'
                        WHEN '20' THEN '2014'
                        WHEN '21' THEN '2015'
                        WHEN '22' THEN '2016'
                        WHEN '23' THEN '2017'
                        WHEN '24' THEN '2017'
                        WHEN '25' THEN '2018'
                        WHEN '26' THEN '2018'
                        WHEN '27' THEN '2019'
                        WHEN '28' THEN '2019'
                        WHEN '29' THEN '2020'
                        WHEN '30' THEN '2021'
                        WHEN '31' THEN '2021'
                        WHEN '32' THEN '2022'
                        ELSE 'metal plate'
                    END

                /* ---------- fallback ---------- */
                ELSE 'metal plate'
            END
        ELSE product_year
    END AS product_year_derived
FROM df_col

"""

In [137]:
df_col_enriched.head()

,contract_num,form_id,brand,model,sub_model,size,color,hardware,material,condition,year_stamp_holo_dc,product_year,estimate_amount,color_segment
0,NaN,6,LOUIS VUITTON,Malle,Malle,Petite 20,Brown,Gold,Canvas,95-98% เหมือนใหม่ (Like New) มีร่องรอยเพียงเล็...,-,NaN,80000,popular
1,NaN,7,CHRISTIAN DIOR,Lady Dior,Lady Dior,Mini 17,Black,Silver,Satin,95-98% เหมือนใหม่ (Like New) มีร่องรอยเพียงเล็...,NaN,NaN,65000,popular
2,NaN,9,LOUIS VUITTON,Noe,Neonoe,BB,Monogram,Gold,Canvas,79-70% (Damaged) ทรงเปลี่ยนชัดเจน สีเฟดชัดเจน ...,2016,NaN,40000,popular
3,2566000039.0,11,CHRISTIAN DIOR,Saddle,Saddle,Mini 20,Red,Gold,Calfskin,100% (New) สินค้าใหม่ ไม่เคยผ่านการใช้งาน และอ...,Mo447wEVG,NaN,60000,unpopular
4,2566000040.0,12,CHRISTIAN DIOR,Be Dior,Be Dior,Small 27,Beige,Gold,Calfskin,95-98% เหมือนใหม่ (Like New) มีร่องรอยเพียงเล็...,M09810TRL,NaN,50000,popular

##### 2. Brand : Hermes

In [138]:
with open("/home/jovyan/data/mapping/synthetic_year_code_map.json", "r", encoding="utf-8") as f:
    HERMES_YEAR_MAP = json.load(f)

In [139]:
def extract_shape_letter(text, shape):
    t = re.sub(r"[()\[\]]", " ", text)
    pattern = rf"([A-Z])\s*{shape}"
    m = re.search(pattern, t)
    return m.group(1) if m else None

In [140]:
def map_hermes_year(row, HERMES_YEAR_MAP):

    if row.get("brand") != "HERMES":
        return pd.Series([row.get("product_year"), row.get("year_letter")])

    raw = row.get("year_stamp_holo_dc")

    # ----------------------------
    # missing
    # ----------------------------
    if pd.isna(raw):
        return pd.Series(["Unknown", "Unknown"])

    s = str(raw).upper().strip()

    # clean
    s = re.sub(r"[()\[\]*]", " ", s)
    s = re.sub(r"SQAURE|SQUAER|SQURE", "SQUARE", s)
    s = re.sub(r"\s+", " ", s).strip()

    if s in {"", "NAN", "จำไม่ได้", "ไม่ระบุ", "ไม่ทราบ", "ไม่แน่ใจ"}:
        return pd.Series(["Unknown", "Unknown"])

    # ----------------------------
    # helper: first letter
    # ----------------------------
    m_letter = re.search(r"[A-Z]", s)
    letter = m_letter.group(0) if m_letter else None

    # ==================================================
    # 1) explicit year (ABSOLUTE PRIORITY)
    # ==================================================
    # 2008/[L] → 2018
    if re.search(r"2008\s*/\s*\[?L\]?", s):
        return pd.Series([2018, "2018"])

    # 2014/H → 2014
    m_year = re.search(r"\b(19|20)\d{2}\b", s)
    if m_year:
        year4 = int(m_year.group())
        return pd.Series([year4, str(year4)])

    # ==================================================
    # 2) SQUARE
    # ==================================================
    letter_sq = extract_shape_letter(s, "SQUARE")
    if letter_sq:
        y = HERMES_YEAR_MAP["square_shape"].get(letter_sq)
        return pd.Series([y if y else "Unknown", f"{letter_sq} Square"])

    # ==================================================
    # 3) CIRCLE
    # ==================================================
    letter_ci = extract_shape_letter(s, "CIRCLE")
    if letter_ci:
        y = HERMES_YEAR_MAP["circle_shape"].get(letter_ci)
        return pd.Series([y if y else "Unknown", f"{letter_ci} Circle"])

    # ==================================================
    # 4) CODE / LETTER+NUMBER → WITHOUT_SHAPE_NEW
    # ==================================================
    if letter and re.search(r"\d", s):
        y_new = HERMES_YEAR_MAP["without_shape_new"].get(letter)
        if y_new:
            return pd.Series([y_new, f"{letter} {y_new}"])

    # ==================================================
    # 5) SINGLE LETTER ONLY
    # ==================================================
    if re.fullmatch(r"[A-Z]", s):
        y_new = HERMES_YEAR_MAP["without_shape_new"].get(s)
        if y_new:
            return pd.Series([y_new, f"{s} {y_new}"])

        # OLD → Unknown
        return pd.Series(["Unknown", s])


    # ==================================================
    # fallback
    # ==================================================
    return pd.Series(["Unknown", "Unknown"])

In [141]:
# map hermes year ด้วย function map_hermes_year
df_col_enriched[["product_year", "year_letter"]] = (
    df_col_enriched.apply(
        lambda r: map_hermes_year(r, HERMES_YEAR_MAP),
        axis=1
    )
)

In [142]:
hermes_mapping = df_col_enriched

#### Feature

##### Create product year segment

In [143]:
# create product_year_segment ของ Chanel เพื่อแยก metal plate และ not metal plate
df_col_enriched["product_year_segment"] = np.where(
    df_col_enriched["brand"] == "CHANEL",
    np.where(
        df_col_enriched["product_year"] == "metal plate",
        "metal plate",
        "not metal plate"
    ),
    "Unknown"
)

In [144]:
df_col_enriched["product_year"] = df_col_enriched["product_year"].fillna("Unknown")
df_col_enriched["year_letter"]  = df_col_enriched["year_letter"].fillna("Unknown")

In [145]:
df_gold = df_col_enriched.drop(columns=["year_stamp_holo_dc"])

In [146]:
info = duckdb.query("""
    SELECT
        COUNT(*) AS total_rows,
        SUM(CASE WHEN estimate_amount IS NULL THEN 1 ELSE 0 END) AS null_count,
        SUM(CASE WHEN estimate_amount = 0 THEN 1 ELSE 0 END) AS zero_count,
        SUM(CASE WHEN estimate_amount IS NOT NULL AND estimate_amount <> 0 THEN 1 ELSE 0 END) AS usable_count
    FROM df_gold
""").to_df()

In [147]:
print(f"""
[Gold Pipeline - estimate_amount]
Total rows     : {int(info.total_rows[0])} ตัว
NULL values    : {int(info.null_count[0])} ตัว
Zero values    : {int(info.zero_count[0])} ตัว
Usable records : {int(info.usable_count[0])} ตัว
""")

[Gold Pipeline - estimate_amount]
Total rows     : 6906 ตัว
NULL values    : 27 ตัว
Zero values    : 86 ตัว
Usable records : 6793 ตัว

In [148]:
df_gold = duckdb.query("select * from df_gold where estimate_amount notnull and estimate_amount <> 0").to_df()

##### Create condition score

In [149]:
mapping_to_score = {
    '100% (New) สินค้าใหม่ ไม่เคยผ่านการใช้งาน และออกจากช๊อปไม่เกิน 12 เดือน': 100,
    "99% ไม่ผ่านการใช้งาน (Kept Unused) ไม่ผ่านการใช้งาน แต่อุปกรณ์ไม่ครบเหมือนออกจากช๊อป": 99,
    "95-98% เหมือนใหม่ (Like New) มีร่องรอยเพียงเล็กน้อยจากการจัดเก็บหรือทดลองใช้งาน": 97,
    "94-90% (Good Condition) ผ่านการใช้งาน มีตำหนิทั่วไป เช่น มุมถลอกหรือรอยขีดเล็กน้อย": 92,
    "89-85% (Fair Condition) มีตำหนิชัดเจน เช่น สีซีด มุมถลอก หรือหนังมีรอยชัดเจน": 87,
    "84-80% (Poor Condition) ทรงเริ่มเปลี่ยน สีซีดจาง หนังเริ่มเสียทรงหรือมีสีเฟดบางส่วน": 82,
    "79-70% (Damaged) ทรงเปลี่ยนชัดเจน สีเฟดชัดเจน มีรอยถลอกหรือขาดชัดเจน": 75,
    "69-60% (Breakage) สภาพทรุดโทรม มีตำหนิหลายจุด ผ่านการซ่อม/เปลี่ยนทรง/เปลี่ยนอะไหล่ หรือซ่อมสี": 65,
    "ต่ำกว่า 59% (Reconsideration) สินค้าชำรุด หรือเปลี่ยนสีทั้งใบ/ทำสี ต้องได้รับการพิจารณาโดยเจ้าหน้าที่ผู้มีอำนาจ": 59
}

# map ก่อน
df_gold['condition_score'] = df_gold['condition'].map(mapping_to_score)

# คำนวณ median จากค่าที่ map ได้
median_value = df_gold['condition_score'].median()

# แทนค่า NaN ด้วย median
df_gold['condition_score'] = df_gold['condition_score'].fillna(median_value)

##### Create condition segment

In [150]:
def condition_segment(score):
    if pd.isna(score):
        return 'Unknown'
    elif score < 82.54416876904165:
        return 'Low Condition'
    elif score < 94.21111748929775:
        return 'Medium Condition'
    else:
        return 'High Condition'

df_gold['condition_segment'] = df_gold['condition_score'].apply(condition_segment)

gold = df_gold

In [151]:
gold.info()

<class 'pandas.DataFrame'>
RangeIndex: 6793 entries, 0 to 6792
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   contract_num          4776 non-null   str
 1   form_id               6793 non-null   int64
 2   brand                 6793 non-null   str
 3   model                 6793 non-null   str
 4   sub_model             6793 non-null   str
 5   size                  6793 non-null   str
 6   color                 6793 non-null   str
 7   hardware              6793 non-null   str
 8   material              6793 non-null   str
 9   condition             6793 non-null   str
 10  product_year          6793 non-null   str
 11  estimate_amount       6793 non-null   int64
 12  color_segment         6793 non-null   str
 13  year_letter           6793 non-null   str
 14  product_year_segment  6793 non-null   str
 15  condition_score       6793 non-null   float64
 16  condition_segment     6793 non-null   str
dtypes: float64(1), int64(2), str(14)
memory usage: 2.7 MB

In [152]:
gold.columns.tolist()

['contract_num',
 'form_id',
 'brand',
 'model',
 'sub_model',
 'size',
 'color',
 'hardware',
 'material',
 'condition',
 'product_year',
 'estimate_amount',
 'color_segment',
 'year_letter',
 'product_year_segment',
 'condition_score',
 'condition_segment']

In [153]:
# บันทึกข้อมูลที่ clean เบื้องต้นแล้วเก็บไว้ที่ gold
df.to_parquet(
    "/home/jovyan/database/gold/gold_jjm_customer_loan.parquet",
    index=False
)

#### Load Data on Gold Warehouse

In [154]:
# 1. จัดการข้อมูลก่อน (ใช้ 'Int64' ตัว i ใหญ่ เพื่อให้เก็บ NaN ในรูปแบบ Integer ได้)
gold['estimate_amount'] = pd.to_numeric(gold['estimate_amount'], errors='coerce').astype('Int64')
gold['form_id'] = pd.to_numeric(gold['form_id'], errors='coerce').astype('Int64')

# เชื่อมต่อ DB
conn = psycopg2.connect(
    host=p.hostname,
    port=p.port,
    user=p.username,
    password=p.password,
    dbname=p.path.lstrip("/")
)
cur = conn.cursor()

# สร้าง Schema / Table (เหมือนเดิม)
cur.execute("CREATE SCHEMA IF NOT EXISTS gold;")
cur.execute("""
CREATE TABLE IF NOT EXISTS gold.jjm_customer_loan (
    contract_num        TEXT,
    form_id             INT,
    brand               TEXT,
    model               TEXT,
    sub_model           TEXT,
    size                TEXT,
    color               TEXT,
    hardware            TEXT,
    material            TEXT,
    condition           TEXT,
    product_year        TEXT,
    estimate_amount     INT,
    color_segment       TEXT,
    year_letter         TEXT,
    product_year_segment TEXT,
    condition_score     FLOAT,
    condition_segment   TEXT  
);
""")
cur.execute("TRUNCATE TABLE gold.jjm_customer_loan;")

# 2. เตรียม Buffer
buffer = StringIO()

# ใช้ quoting=1 (quote non-numeric) เพื่อความชัวร์ หรือใช้ na_rep='' ปกติ
gold.to_csv(buffer, index=False, header=False, na_rep='')
buffer.seek(0)

# 3. ใช้คำสั่ง COPY ที่ระบุ NULL ชัดเจน
try:
    cur.copy_expert(
        """
        COPY gold.jjm_customer_loan 
        FROM STDIN 
        WITH (FORMAT CSV, NULL '', ENCODING 'UTF8')
        """,
        buffer
    )
    conn.commit()
    print("Data successfully loaded into gold.jjm_customer_loan.")
except Exception as e:
    conn.rollback()
    print(f"Error: {e}")
finally:
    cur.close()
    conn.close()

Data successfully loaded into gold.jjm_customer_loan.